In [14]:
import numpy as np
from scipy.special import softmax

In [3]:
mat = np.array([[1,0,1,0], [0,1,1,0]]).T

In [6]:
mat

array([[1, 0],
       [0, 1],
       [1, 1],
       [0, 0]])

In [11]:
res = mat @ mat.T

In [12]:
res

array([[1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 1, 2, 0],
       [0, 0, 0, 0]])

In [17]:
ans = softmax(res, axis = 1) @ mat

In [18]:
ans

array([[0.73105858, 0.5       ],
       [0.5       , 0.73105858],
       [0.73105858, 0.73105858],
       [0.5       , 0.5       ]])